spring:
  cloud:
    stream:
      bindings:
        output:
          destination: tp-kinesis-stream
          content-type: text/plain

cloud:
  aws:
    credentials:
      accessKey: AKIARZDR7BLZNDQLMCNX
      secretKey: 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
    region:
      static: us-east-1
    stack:
      auto: false